name: 'addcommenttopullandissuesfrompushaction'
description: 'add comment to pull and issues from push workflow'
author: 'tony hallett'
inputs:
  addTo:
    description: add to pull or issues or pullandissues
    required: true
    default: issues
  caseSensitive:
    description: should matching be case sensitive
    required: false
    default: 'false'
  closeWords:
    description: words that indicate associated issue
    required: false
    default: 'close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved'
  usePullTitle:
    description: look in the pull request title for issues
    required: false
    default: 'true'
  usePullBody:
    description: look in the pull request body for issues
    required: false
    default: 'true'
  useCommitMessages:
    description: look in the pull request commit messages for issues
    required: false
    default: 'true'
  useBranch:
    description: look in the pull request branch name for issues
    required: false
    default: 'true'
  branchIssuesWords:
    description: words that form part of an issue branch name
    required: false
    default: 'issue, issues'
  branchDelimiters:
    description: delimiters of a matching branch name
    required: false
    default: '_, -'
outputs:
  commentIds:
    description: ids of created comments 
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'message-square'
  color: 'green'
